export const CREATE_PRAYER = 'CREATE_PRAYER';
export const GET_PRAYER = 'GET_PRAYER';
export const UPDATE_PRAYER = 'UPDATE_PRAYER';
export const DELETE_PRAYER = 'DELETE_PRAYER';

export const CREATE_PRAYER_ERROR = 'CREATE_PRAYER_ERROR';
export const GET_PRAYER_ERROR = 'GET_PRAYER_ERROR';
export const UPDATE_PRAYER_ERROR = 'UPDATE_PRAYER_ERROR';
export const DELETE_PRAYER_ERROR = 'DELETE_PRAYER_ERROR';
